project:
  type: book

book:
  title: "Toolbox Computational Social Science"
  author: "Felix Lennert"
  date: "2024-01-04"
  chapters:
    - index.qmd
    - catch-up.qmd
    - stringr_regex.qmd
    - scraping-I.qmd
    - scraping-II.qmd
    - text-preprocessing.qmd
    - supervised_ml.qmd
    - unsupervised_ml.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

